# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imprimir_medico.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ImpMed(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(140, 211, 238);  /* Cor de fundo */")
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-20, 160, 801, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 130, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: white;  /* Cor de fundo */\n"
"    color: rgb(65, 150, 183);  /* Cor do texto */\n"
"    border-radius: 10px;  /* Raio dos cantos */\n"
"    padding: 10px 20px;  /* Preenchimento interno */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(8, 113, 155);  /* Cor de fundo ao passar o mouse */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 801, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 100, 491, 22))
        self.lineEdit_5.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_bus_cpf = QtWidgets.QLabel(self.centralwidget)
        self.label_bus_cpf.setGeometry(QtCore.QRect(54, 100, 71, 21))
        self.label_bus_cpf.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_bus_cpf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bus_cpf.setObjectName("label_bus_cpf")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 500, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: white;  /* Cor de fundo */\n"
"    color: rgb(65, 150, 183);  /* Cor do texto */\n"
"    border-radius: 10px;  /* Raio dos cantos */\n"
"    padding: 10px 20px;  /* Preenchimento interno */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(8, 113, 155);  /* Cor de fundo ao passar o mouse */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(190, 0, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 180, 161, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 180, 511, 301))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_16.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_6.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_17.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_6.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_18.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_6.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_19.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_6.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_20.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_6.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_21.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_6.addWidget(self.lineEdit_21)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_22.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_6.addWidget(self.lineEdit_22)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_24.setStyleSheet("background-color: white;  /* Cor de fundo */")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_6.addWidget(self.lineEdit_24)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "BUSCA"))
        self.pushButton.setText(_translate("MainWindow", "BUSCAR"))
        self.label_bus_cpf.setText(_translate("MainWindow", "CPF:"))
        self.pushButton_2.setText(_translate("MainWindow", "VOLTAR"))
        self.label_13.setText(_translate("MainWindow", "IMPRIMIR MÉDICO"))
        self.label_19.setText(_translate("MainWindow", "NOME:"))
        self.label_20.setText(_translate("MainWindow", "TELEFONE:"))
        self.label_21.setText(_translate("MainWindow", "NASCIMENTO:"))
        self.label_22.setText(_translate("MainWindow", "EMAIL:"))
        self.label_23.setText(_translate("MainWindow", "ESPECIALIDADE:"))
        self.label_24.setText(_translate("MainWindow", "HORA DE ATENDIMENTO:"))
        self.label_25.setText(_translate("MainWindow", "CRM:"))
        self.label_18.setText(_translate("MainWindow", "SENHA:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ImpMed()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
