string = "ENQUANTO A ÊNFASE DE TAYLOR ESTAVA NAS TAREFAS, FAYOL PARTIA DA VISÃO MACROSCÓPICA DA ORGANIZAÇÃO, FOCANDO AS FUNÇÕES DE GERENCIMENTO E A ESTRUTURA ORGANIZACIONAL."
result = string.lower()
print(result)